engines:
  duplication:
    enabled: true
    config:
      languages:
      - java
  checkstyle:
    enabled: true
    channel: "beta"
  fixme:
    enabled: true
ratings:
  paths:
  - "**.java"
  - "**.xml"
exclude_paths: ["docs/**", "**.png"]
