engines:
  duplication:
    enabled: true
    config:
      languages:
      - java
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.java"
  - "**.xml"
exclude_paths: ["docs/**"]
