engines:
  duplication:
    enabled: true
    config:
      languages:
      - java
  checkstyle:
    enabled: false
    channel: "beta"
    checks:
      com.puppycrawl.tools.checkstyle.checks.javadoc:
        enabled: false
  fixme:
    enabled: true
ratings:
  paths:
  - "**.java"
  - "**.xml"
exclude_paths: ["docs/**", "**.png"]
