language: android

android:
  components:
    - android-25
    - build-tools-27.0.3
    - extra-android-m2repository
    
branches:
  only:
    - master

notifications:
  email: false
  
before_install:
- export ANDROID_HOME=/usr/local/android-sdk
- echo "sdk.dir=$ANDROID_HOME" > local.properties
