language: android

android:
  components:
    - android-25
    - build-tools-27.0.3
    
before_install:
  - export ANDROID_HOME=/usr/local/android-sdk
  - echo "sdk.dir=$ANDROID_HOME" > local.properties

install:
  - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2"
  
script:
  - ./gradlew install -xjavadoc


notifications:
  email: false
  
